//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnidoc {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Omnidoc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_BufferingStreamMustBeSeekable {
            get {
                return ResourceManager.GetString("Error_BufferingStreamMustBeSeekable", resourceCulture);
            }
        }
        
        internal static string Error_FailedToAddContent {
            get {
                return ResourceManager.GetString("Error_FailedToAddContent", resourceCulture);
            }
        }
        
        internal static string Error_FailedToCreateBufferStream {
            get {
                return ResourceManager.GetString("Error_FailedToCreateBufferStream", resourceCulture);
            }
        }
        
        internal static string Error_FailedToRemoveContent {
            get {
                return ResourceManager.GetString("Error_FailedToRemoveContent", resourceCulture);
            }
        }
        
        internal static string Error_InvalidAttachment {
            get {
                return ResourceManager.GetString("Error_InvalidAttachment", resourceCulture);
            }
        }
        
        internal static string Error_InvalidDataUri {
            get {
                return ResourceManager.GetString("Error_InvalidDataUri", resourceCulture);
            }
        }
        
        internal static string Error_InvalidFormat {
            get {
                return ResourceManager.GetString("Error_InvalidFormat", resourceCulture);
            }
        }
        
        internal static string Error_MalformedDocument {
            get {
                return ResourceManager.GetString("Error_MalformedDocument", resourceCulture);
            }
        }
        
        internal static string Error_MustBeNonNegative {
            get {
                return ResourceManager.GetString("Error_MustBeNonNegative", resourceCulture);
            }
        }
        
        internal static string Error_StreamMustBeSeekable {
            get {
                return ResourceManager.GetString("Error_StreamMustBeSeekable", resourceCulture);
            }
        }
        
        internal static string Error_TypeMismatch {
            get {
                return ResourceManager.GetString("Error_TypeMismatch", resourceCulture);
            }
        }
        
        internal static string Error_UnsupportedConverterChain {
            get {
                return ResourceManager.GetString("Error_UnsupportedConverterChain", resourceCulture);
            }
        }
    }
}
